name: dogsay
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: It's like cowsay, but with a dog.
description: |
  Woof

grade: stable
confinement: strict

apps:
  dogsay:
    command: bin/dogsay

parts:
  dogsay:
    source: .
    plugin: ruby
    gems:
      - dogsay
